Vehicles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('automobiles.urls')),
                  path('users/', include('users.urls')),
                  path('users/', include('django.contrib.auth.urls')),
                  path("contact/", include('contact.urls')),
                  path("pricing/", include('pricing.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pricing/urls.py
from django.urls import path
from . import views

app_name = 'pricing'
urlpatterns = [
    path("", views.pricing, name="pricing"),
    path("pay_3", views.pay_3, name="pay_3"),
    path("pay_6", views.pay_6, name="pay_6"),
    path("pay_9", views.pay_9, name="pay_9"),
    path("pay_12", views.pay_12, name="pay_12"),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register_user/", views.register_user, name="register_user"),
    path("delete_user/", views.delete_user, name="delete_user"),
    path("login_user/", views.login_user, name="logins"),
]

pricing/models.py
from django.db import models

# Create your models here.

pricing/views.py
from django.shortcuts import render


# Create your views here.

def pricing(request):
    return render(request, 'pricing/index.html')


def pay_3(request):
    return render(request, 'pay/pay_3.html')


def pay_6(request):
    return render(request, 'pay/pay_6.html')


def pay_9(request):
    return render(request, 'pay/pay_9.html')


def pay_12(request):
    return render(request, 'pay/pay_12.html')

pricing/templates/pricing/index.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}<br/>
<center><h1>PRICING</h1></center>
<div class="container mb-5 mt-5">
    <div class="pricing card-deck flex-column flex-md-row mb-3">
        <div class="card card-pricing text-center px-3 mb-4">
            <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white shadow-sm">Starter</span>
            <div class="bg-transparent card-header pt-4 border-0">
                <h1 class="h1 font-weight-normal text-primary text-center mb-0"
                    data-pricing-value="15">$<span
                        class="price">3</span>
                    <p><span class="h6 text-muted ml-2">/ per month</span></p>
                </h1>
            </div>
            <div class="card-body pt-0">
                <ul class="list-unstyled mb-4">
                    <li>Up to 3 users</li>
                    <li>Basic support</li>
                    <li>Yearly updates</li>
                    <li>Free cancelation</li>
                </ul>
                <form action="{% url 'pricing:pay_3' %}" method="post">
                    {% csrf_token %}
                    <button type="submit"
                            class="btn btn-outline-secondary mb-3 hvr">Order
                        now
                    </button>
                </form>
            </div>
        </div>
        <div class="card card-pricing popular shadow text-center px-3 mb-4">
            <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white shadow-sm">Professional</span>
            <div class="bg-transparent card-header pt-4 border-0">
                <h1 class="h1 font-weight-normal text-primary text-center mb-0"
                    data-pricing-value="30">$<span
                        class="price">6</span>
                    <p><span class="h6 text-muted ml-2">/ per month</span></p>
                </h1>
            </div>
            <div class="card-body pt-0">
                <ul class="list-unstyled mb-4">
                    <li>Up to 5 users</li>
                    <li>Email Support support</li>
                    <li>Monthly updates</li>
                    <li>Free cancelation</li>
                </ul>
                <form action="{% url 'pricing:pay_6' %}" method="post">
                    {% csrf_token %}
                    <button type="submit"
                            class="btn btn-outline-secondary mb-3 hvr">Order
                        now
                    </button>
                </form>
            </div>
        </div>
        <div class="card card-pricing text-center px-3 mb-4">
            <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white shadow-sm">Business</span>
            <div class="bg-transparent card-header pt-4 border-0">
                <h1 class="h1 font-weight-normal text-primary text-center mb-0"
                    data-pricing-value="45">$<span
                        class="price">9</span>
                    <p><span class="h6 text-muted ml-2">/ per month</span></p>
                </h1>
            </div>
            <div class="card-body pt-0">
                <ul class="list-unstyled mb-4">
                    <li>Up to 10 users</li>
                    <li>Email & phone support</li>
                    <li>Monthly updates</li>
                    <li>Free cancelation</li>
                </ul>
                <form action="{% url 'pricing:pay_9' %}" method="post">
                    {% csrf_token %}
                    <button type="submit"
                            class="btn btn-outline-secondary mb-3 hvr">Order
                        now
                    </button>
                </form>
            </div>
        </div>
        <div class="card card-pricing text-center px-3 mb-4">
            <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white shadow-sm">Enterprise</span>
            <div class="bg-transparent card-header pt-4 border-0">
                <h1 class="h1 font-weight-normal text-primary text-center mb-0"
                    data-pricing-value="60">$<span
                        class="price">12</span>
                    <p><span
                            class="h6 text-muted ml-2">/ per month</span></p>
                </h1>
            </div>
            <div class="card-body pt-0">
                <ul class="list-unstyled mb-4">
                    <li>Up to 20 users</li>
                    <li>24h support</li>
                    <li>Monthly updates</li>
                    <li>Free cancelation</li>
                </ul>
                <form action="{% url 'pricing:pay_12' %}" method="post">
                    {% csrf_token %}
                    <button type="submit"
                            class="btn btn-outline-secondary mb-3 hvr">Order
                        now
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock page_header %}
{% block content %}
{% include 'footer.html' %}
{% endblock content %}