Vehicles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('automobiles.urls')),
                  path('users/', include('users.urls')),
                  path('users/', include('django.contrib.auth.urls')),
                  path("contact/", include('contact.urls')),
                  path("pricing/", include('pricing.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

automobiles/urls.py
from django.urls import path
from . import views

app_name = "automobiles"
urlpatterns = [
    path("", views.home, name="home"),
    path("add_vehicle/", views.add_vehicle, name="add_vehicle"),
    path("all_vehicles/", views.all_vehicles, name="all_vehicles"),
    path("list_vehicles/", views.list_vehicles, name="list_vehicles"),
    path("show_vehicle/<vehicle_id>", views.show_vehicle, name="show_vehicle"),
    path("search_vehicles/", views.search_vehicles, name="search_vehicles"),
    path("update_vehicle/<vehicle_id>", views.update_vehicle,
         name="update_vehicle"),
    path("list_brand/", views.list_brand, name="list_brand"),
    path("show_brand/<brand_id>", views.show_brand, name="show_brand"),
    path("update_brand/<brand_id>", views.update_brand, name="update_brand"),
    path("add_brand/", views.add_brand, name="add_brand"),
    path("list_model/", views.list_model, name="list_model"),
    path("show_model/<model_id>", views.show_model, name="show_model"),
    path("update_model/<model_id>", views.update_model, name="update_model"),
    path("add_model/", views.add_model, name="add_model"),
    path("list_driver/", views.list_driver, name="list_driver"),
    path("show_driver/<driver_id>", views.show_driver, name="show_driver"),
    path("update_driver/<driver_id>", views.update_driver,
         name="update_driver"),
    path("add_driver/", views.add_driver, name="add_driver"),
    path("delete_vehicle/<vehicle_id>", views.delete_vehicle,
         name="delete_vehicle"),
    path("delete_brand/<brand_id>", views.delete_brand, name="delete_brand"),
    path("delete_driver/<driver_id>", views.delete_driver,
         name="delete_driver"),
    path("delete_model/<model_id>", views.delete_model, name="delete_model"),
    path("vehicle_text", views.vehicle_text, name="vehicle_text"),
    path("vehicle_csv", views.vehicle_csv, name="vehicle_csv"),
    path("vehicle_pdf", views.vehicle_pdf, name="vehicle_pdf"),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path("", views.index, name="msg_me"),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register_user/", views.register_user, name="register_user"),
    path("delete_user/", views.delete_user, name="delete_user"),
    path("login_user/", views.login_user, name="logins"),
]

automobiles/models.py
from django.db import models


# Create your models here.
class Brand(models.Model):
    name = models.CharField('Brand', max_length=10)

    def __str__(self):
        return self.name.title()


class Model(models.Model):
    name = models.CharField('Model', max_length=10)

    def __str__(self):
        return self.name.title()


class Driver(models.Model):
    first_name = models.CharField('First Name', max_length=30)
    last_name = models.CharField('Last Name', max_length=30)

    def __str__(self):
        return self.first_name.title() + ' ' + self.last_name.title()


class Vehicle(models.Model):
    name = models.CharField('Name', max_length=20)  # blank=False,
    brand = models.ForeignKey(Brand, blank=True, null=True, on_delete=models.CASCADE)  # null=True
    model = models.ForeignKey(Model, blank=True, null=True, on_delete=models.CASCADE)  # null=True
    reg_num = models.CharField('Registration Number', max_length=10, blank=True)
    tech_inspection = models.DateField("Technical Inspection", blank=True, null=True)
    vin_num = models.CharField('VIN Number', max_length=17, blank=True)
    driver = models.ManyToManyField(Driver, blank=True)
    description = models.TextField(blank=True)
    vehicle_image = models.ImageField(blank=True, null=True, upload_to="images/")

    def __str__(self):
        return self.name.title()

automobiles/forms.py
from django import forms
from django.forms import ModelForm
from .models import Vehicle, Brand, Model, Driver


class VehicleForm(ModelForm):
    class Meta:
        model = Vehicle
        fields = ['name', 'brand', 'model', 'reg_num', 'vin_num',
                  'tech_inspection', 'driver',
                  'description', 'vehicle_image']
        labels = {
            'name': '',
            'Brand': 'Brand',
            'model': 'Model',
            'reg_num': '',
            'vin_num': '',
            'tech_inspection': '',
            'driver': 'Driver/s',
            'description': '',
            'vehicle_image': '',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control',
                                           'placeholder': 'Vehicle Name'}),
            'brand': forms.Select(attrs={'class': 'form-select',
                                         'placeholder': 'Vehicle Brand'}),
            'model': forms.Select(attrs={'class': 'form-select',
                                         'placeholder': 'Vehicle Model'}),
            'reg_num': forms.TextInput(attrs={'class': 'form-control',
                                              'placeholder': 'Registry Number'}),
            'vin_num': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'VIN'}),
            'tech_inspection': forms.DateInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Technical Inspection Date (YYYY:MM:DD)'}),
            'driver': forms.SelectMultiple(
                attrs={'class': 'form-control', 'placeholder': 'Driver'}),
            'description': forms.Textarea(
                attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }


class BrandForm(ModelForm):
    class Meta:
        model = Brand
        fields = ['name']
        labels = {
            'name': '',
        }
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Brand Name'}),
        }


class ModelForm(ModelForm):
    class Meta:
        model = Model
        fields = ['name']
        labels = {
            'name': '',
        }
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Model Name'}),
        }


class DriverForm(ModelForm):
    class Meta:
        model = Driver
        fields = ['first_name', 'last_name']
        labels = {
            'first_name': '',
            'last_name': '',
        }
        widgets = {
            'first_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
        }

automobiles/views.py
from django.shortcuts import render, redirect
from .forms import VehicleForm, BrandForm, ModelForm, DriverForm
from datetime import datetime
from .models import Brand, Model, Vehicle, Driver
from django.http import HttpResponseRedirect, HttpResponse

# CSV import
import csv

# PDF imports
from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

# Pagination imports
from django.core.paginator import Paginator


def home(request):
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')

    context = {"current_year": current_year, 'time': time}
    return render(request, "home.html", context)


def add_vehicle(request):
    submitted = False
    if request.method == "POST":
        form = VehicleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('?submitted=True')
    else:
        form = VehicleForm()
        if 'submitted' in request.GET:
            submitted = True

    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    context = {"form": form, "current_year": current_year, 'time': time,
               'submitted': submitted}
    return render(request, "add_vehicle.html", context)


def all_vehicles(request):
    vehicles_all = Vehicle.objects.all().order_by('name')
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')

    context = {'vehicles_all': vehicles_all, "current_year": current_year,
               'time': time}
    return render(request, 'all_vehicles.html', context)


def list_vehicles(request):
    vehicles_list = Vehicle.objects.all()
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')

    # Set up Pagination
    p = Paginator(Vehicle.objects.all(), 4)
    page = request.GET.get('page')
    vehicles = p.get_page(page)
    nums = '-' * vehicles.paginator.num_pages

    context = {'vehicles_list': vehicles_list, "current_year": current_year,
               'time': time, 'vehicles': vehicles,
               'nums': nums}
    return render(request, 'list_vehicles.html', context)


def show_vehicle(request, vehicle_id):
    vehicle_show = Vehicle.objects.get(pk=vehicle_id)
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')

    context = {'vehicle_show': vehicle_show, "current_year": current_year,
               'time': time}
    return render(request, 'show_vehicle.html', context)


def search_vehicles(request):
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    if request.method == 'POST':
        searched = request.POST['searched']
        vehicles = Vehicle.objects.filter(name__contains=searched)
        return render(request, 'search_vehicles.html',
                      {'searched': searched, 'vehicles': vehicles,
                       "current_year": current_year, 'time': time})
    else:
        vehicles_search = Vehicle.objects.all()
        context = {'vehicles_search': vehicles_search,
                   "current_year": current_year, 'time': time}
        return render(request, 'search_vehicles.html', context)


def update_vehicle(request, vehicle_id):
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    vehicle_update = Vehicle.objects.get(pk=vehicle_id)
    form = VehicleForm(request.POST or None, request.FILES or None,
                       instance=vehicle_update)
    if form.is_valid():
        form.save()
        redirect('update_vehicle.html')

    context = {"form": form, 'vehicle_update': vehicle_update,
               "current_year": current_year, 'time': time}
    return render(request, 'update_vehicle.html', context)


def list_brand(request):
    brand_list = Brand.objects.all()
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    p = Paginator(Brand.objects.all(), 4)
    page = request.GET.get('page')
    brands = p.get_page(page)
    nums = '-' * brands.paginator.num_pages

    context = {'brand_list': brand_list, "current_year": current_year,
               'time': time, 'brands': brands,
               'nums': nums}
    return render(request, 'list_brand.html', context)


def show_brand(request, brand_id):
    brand_show = Brand.objects.get(pk=brand_id)
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    context = {'brand_show': brand_show, "current_year": current_year,
               'time': time}
    return render(request, 'show_brand.html', context)


def update_brand(request, brand_id):
    brand_update = Brand.objects.get(pk=brand_id)
    form = BrandForm(request.POST or None, instance=brand_update)
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    if form.is_valid():
        form.save()
        redirect('update_brand.html')

    context = {"form": form, 'brand_update': brand_update,
               "current_year": current_year, 'time': time}
    return render(request, 'update_brand.html', context)


def add_brand(request):
    submitted = False
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    if request.method == "POST":
        form = BrandForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('?submitted=True')
    else:
        form = BrandForm()
        if 'submitted' in request.GET:
            submitted = True

    context = {"form": form, 'submitted': submitted,
               "current_year": current_year, 'time': time}
    return render(request, "add_brand.html", context)


def list_model(request):
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    model_list = Model.objects.all()
    p = Paginator(Model.objects.all(), 4)
    page = request.GET.get('page')
    models = p.get_page(page)
    nums = '-' * models.paginator.num_pages
    context = {'model_list': model_list, "current_year": current_year,
               'time': time, 'models': models,
               'nums': nums}
    return render(request, 'list_model.html', context)


def show_model(request, model_id):
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    model_show = Model.objects.get(pk=model_id)
    context = {'model_show': model_show, "current_year": current_year,
               'time': time}
    return render(request, 'show_model.html', context)


def update_model(request, model_id):
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    model_update = Model.objects.get(pk=model_id)
    form = ModelForm(request.POST or None, instance=model_update)
    if form.is_valid():
        form.save()
        redirect('update_model.html')

    context = {"form": form, 'model_update': model_update,
               "current_year": current_year, 'time': time}
    return render(request, 'update_model.html', context)


def add_model(request):
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    submitted = False
    if request.method == "POST":
        form = ModelForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('?submitted=True')
    else:
        form = ModelForm()
        if 'submitted' in request.GET:
            submitted = True

    context = {"form": form, 'submitted': submitted,
               "current_year": current_year, 'time': time}
    return render(request, "add_model.html", context)


def list_driver(request):
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    driver_list = Driver.objects.all()
    p = Paginator(Driver.objects.all(), 2)
    page = request.GET.get('page')
    drivers = p.get_page(page)
    nums = '-' * drivers.paginator.num_pages
    context = {'driver_list': driver_list, "current_year": current_year,
               'time': time,'drivers': drivers,
               'nums': nums}
    return render(request, 'list_driver.html', context)


def show_driver(request, driver_id):
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    driver_show = Driver.objects.get(pk=driver_id)
    context = {'driver_show': driver_show, "current_year": current_year,
               'time': time}
    return render(request, 'show_driver.html', context)


def update_driver(request, driver_id):
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    driver_update = Driver.objects.get(pk=driver_id)
    form = DriverForm(request.POST or None, instance=driver_update)
    if form.is_valid():
        form.save()
        redirect('update_driver.html')

    context = {"form": form, 'driver_update': driver_update,
               "current_year": current_year, 'time': time}
    return render(request, 'update_driver.html', context)


def add_driver(request):
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    submitted = False
    if request.method == "POST":
        form = DriverForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('?submitted=True')
    else:
        form = DriverForm()
        if 'submitted' in request.GET:
            submitted = True

    context = {"form": form, 'submitted': submitted,
               "current_year": current_year, 'time': time}
    return render(request, "add_driver.html", context)


def delete_vehicle(request, vehicle_id):
    now = datetime.now()
    current_year = now.year
    time = now.strftime('%H:%M:%S')
    vehicle_delete = Vehicle.objects.get(pk=vehicle_id)
    vehicle_delete.delete()
    context = {"current_year": current_year, 'time': time}

automobiles/templates/add_brand.html
{% extends 'base.html' %}
{% block page_header %}
{% endblock page_header %}
{% block content %}

<br/>
<center><h1>ADD BRAND</h1></center><br/>
{% if submitted %}
<div class="alert alert-success" role="alert">
    <center>Your BRAND Was Submitted Succesfully !!!</center>
</div><br/>
<button type="submit" class="btn btn-outline-success mb-3 hvr text-warning">
    <a href="{% url 'automobiles:add_brand' %}">Add Next Brand</a>
</button>
<button class="btn btn-outline-success mb-3 hvr text-warning">
    <a href="{% url 'automobiles:home' %}">Home</a>
</button>
{% else %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}<br/>
    <button type="submit" class="btn btn-outline-info mb-3 hvr text-dark">
        Add
    </button>
    <button type="submit" class="btn btn-outline-info mb-3 hvr text-info" style="margin-left: 25px;">
        <a href="{% url 'automobiles:home' %}">Home &raquo;&raquo;&raquo;</a>
    </button>
</form>

{% endif %}
{% include 'footer.html' %}
{% endblock %}

automobiles/templates/add_driver.html
{% extends 'base.html' %}
{% block page_header %}
{% endblock page_header %}
{% block content %}

<br/>
<center><h1>ADD DRIVER</h1></center><br/>
{% if submitted %}
<div class="alert alert-success" role="alert">
    <center>Your DRIVER Was Submitted Succesfully !!!</center>
</div><br/>
<button type="submit" class="btn btn-outline-success mb-3 hvr text-warning">
    <a href="{% url 'automobiles:add_driver' %}">Add Next Driver</a>
</button>
<button class="btn btn-outline-success mb-3 hvr text-warning">
    <a href="{% url 'automobiles:home' %}">Home</a>
</button>
{% else %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-info mb-3 hvr text-dark">Add
    </button>
    <button type="submit" class="btn btn-outline-info mb-3 hvr text-info" style="margin-left: 25px;">
        <a href="{% url 'automobiles:home' %}">Home &raquo;&raquo;&raquo;</a>
    </button>
</form>

{% endif %}
{% include 'footer.html' %}
{% endblock %}

automobiles/templates/add_model.html
{% extends 'base.html' %}
{% block page_header %}
{% endblock page_header %}
{% block content %}

<br/>
<center><h1>ADD MODEL</h1><br/></center>
{% if submitted %}
<div class="alert alert-success" role="alert">
    <center>Your Model Was Submitted Succesfully !!!</center>
</div><br/>
<button type="submit" class="btn btn-outline-success mb-3 hvr text-warning">
    <a href="{% url 'automobiles:add_model' %}">Add Next Model</a>
</button>
<button class="btn btn-outline-success mb-3 hvr text-warning">
    <a href="{% url 'automobiles:home' %}">Home</a>
</button>
{% else %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-info mb-3 hvr text-dark">Add
    </button>
    <button type="submit" class="btn btn-outline-info mb-3 hvr text-info" style="margin-left: 25px;">
        <a href="{% url 'automobiles:home' %}">Home &raquo;&raquo;&raquo;</a>
    </button>
</form>

{% endif %}
{% include 'footer.html' %}
{% endblock %}

automobiles/templates/footer.html
<div class="space"></div>
<hr class="my-1">
<footer class="absolute">
    <div class="left">&copy; {{ current_year }} All rights reserved</div>
<!--    <center>{{ time }} </center>-->
    <div class="right">
        <a href="https://github.com/0xbm"><i class="fa-brands fa-square-github fa-xl"></i></a>
        <a href="https://www.linkedin.com"><i class="fa-brands fa-square-twitter fa-xl"></i></a>
        <a href="https://www.linkedin.com"><i class="fa-brands fa-linkedin fa-xl"></i></a>
        <a href="{% url 'contact:msg_me' %}"><i class="fa-solid fa-envelope fa-xl"></i></a>
    </div>
</footer>

automobiles/templates/list_brand.html
{% extends 'base.html' %}
{% block page_header %}
{% endblock page_header %}
{% block content %}

<br/>
<center><h1>BRAND LIST</h1></center><br/>
<table class="table table-light table-striped table-hover table-bordered">
    {% for brand in brands %}
    <tr>
        <td>
            <a href="{% url 'automobiles:show_brand' brand.id %}">
                {{ brand.id }}. {{ brand }}
            </a>
        </td>
        <td class="edit_button">
            <a href="{% url 'automobiles:update_brand' brand.id %}"
               class="btn btn-outline-secondary btn-sm">
                Edit
            </a>
            <a href="{% url 'automobiles:delete_brand' brand.id %}"
               class="btn btn-outline-danger btn-sm">
                Delete
            </a>
        </td>
    </tr>
    {% endfor %}
</table>
<br/><br/>
<center>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if brands.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo
                    First</a></li>
                <li class="page-item"><a class="page-link"
                                         href="?page={{ brands.previous_page_number }}">Previous</a>
                </li>
            {% endif %}
            {% for i in nums %}
                <li class="page-item"><a class="page-link"
                                         href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
            {% endfor %}
            {% if brands.has_next %}
                <li class="page-item"><a class="page-link"
                                         href="?page={{ brands.next_page_number }}">Next</a>
                </li>
                <li class="page-item"><a class="page-link"
                                         href="?page={{ brands.paginator.num_pages }}">Last
                    &raquo</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</center>

{% include 'footer.html' %}
{% endblock %}

automobiles/templates/list_driver.html
{% extends 'base.html' %}
{% block page_header %}
{% endblock page_header %}
{% block content %}

<br/>
<center><h1>DRIVER LIST</h1><br/></center>
<table class="table table-light table-striped table-hover table-bordered">
    {% for driver in drivers %}
    <tr>
        <td>
            <a href="{% url 'automobiles:show_driver' driver.id %}">
                {{ driver.id }}. {{ driver }}</a>
        </td>
        <td class="edit_button">
            <a href="{% url 'automobiles:update_driver' driver.id %}"
               class="btn btn-outline-secondary btn-sm">
                Edit
            </a>
            <a href="{% url 'automobiles:delete_driver' driver.id %}"
               class="btn btn-outline-danger btn-sm">
                Delete
            </a>
    </tr>
    {% endfor %}
</table>
<br/><br/>
<center>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if drivers.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo
                First</a></li>
            <li class="page-item"><a class="page-link"
                                     href="?page={{ drivers.previous_page_number }}">Previous</a>
            </li>
            {% endif %}
            {% for i in nums %}
            <li class="page-item"><a class="page-link"
                                     href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
            {% endfor %}
            {% if drivers.has_next %}
            <li class="page-item"><a class="page-link"
                                     href="?page={{ drivers.next_page_number }}">Next</a>
            </li>
            <li class="page-item"><a class="page-link"
                                     href="?page={{ drivers.paginator.num_pages }}">Last
                &raquo</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</center>

{% include 'footer.html' %}
{% endblock %}

automobiles/templates/search_vehicles.html
{% extends 'base.html' %}
{% block page_header %}
{% endblock page_header %}
{% block content %}

<center>
    {% if searched %}<br/>
    <h1>You Serched For {{ searched }}</h1><br/>
    {% for vehicle in vehicles %}
    <a href="{% url 'automobiles:show_vehicle' vehicle.id %}">{{ vehicle }} -
        {{ vehicle.reg_num }}</a>
    <br/>
    {% endfor %}
    {% else %}<br/>
    <div class="alert alert-warning alert-dismissible fade show"
         role="alert">
        <center>
            <p>You Forgot To Search For A Vehicle</p>
            <button type="button" class="close" data-dismiss="alert"
                    aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </center>
    </div>
    {{ vehicle.vehicles_search }}
    {% endif %}
</center>

{% include 'footer.html' %}
{% endblock %}

automobiles/templates/show_brand.html
{% extends 'base.html' %}
{% block page_header %}
{% endblock page_header %}
{% block content %}

<br/><center>
    <br/>
    <div class="card">
        <div class="card-header">
            {{brand_show.id}}. {{ brand_show }}
        </div>
        <div class="card-body">
            <p class="card-text">
            <ul>
                Brand Name: {{ brand_show.name }}<br/>
            </ul>
            </p>
        </div>
    </div>
    <br/>

</center>

{% include 'footer.html' %}
{% endblock %}

automobiles/templates/show_driver.html
{% extends 'base.html' %}
{% block page_header %}
{% endblock page_header %}
{% block content %}

<center>
    <br/>
    <div class="card">
        <div class="card-header">
            {{driver_show.id}}. {{ driver_show }}
        </div>
        <div class="card-body">
            <h6 class="card-title"></h6>
            <p class="card-text">
            <ul>
                First Name: {{ driver_show.first_name }}<br/>
                Last Name: {{ driver_show.last_name }}<br/>
            </ul>
            </p>
        </div>
    </div>
    <br/>

</center>
{% include 'footer.html' %}

{% endblock %}

automobiles/templates/show_vehicle.html
{% extends 'base.html' %}
{% block page_header %}
{% endblock page_header %}
{% block content %}<br/>
<center>
    <br/>
    <div class="card">
        <div class="card-header">
            <strong>{{vehicle_show.id}}. {{ vehicle_show }}</strong>
        </div>
        <div class="card-body">
            <p class="card-text">
                <ul>
                    Registration Number: {{ vehicle_show.reg_num }}<br/>
                    Technical Inspection: {{ vehicle_show.tech_inspection }}<br/>
                    VIN: {{ vehicle_show.vin_num }}<br/>
                    Description: {{ vehicle_show.description }}<br/>
                </ul>
            </p>
            {% if vehicle.vehicle_image %}
            <img class='size' src="{{ vehicle.vehicle_image.url }}" width="200"
                 height="200" alt="" style="margin-left: 550px;  position: absolute;
top:50px"/>
            {% endif %}
        </div>
    </div>
    <br/><br/>
</center>
{% include 'footer.html' %}

{% endblock %}

automobiles/templates/update_driver.html
{% extends 'base.html' %}
{% block page_header %}
{% endblock page_header %}
{% block content %}
<h1>Edit {{ driver_update }} {{ driver_update.name }}</h1><br/>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}<br/>
    <button type="submit" class="btn btn-outline-info mb-3 hvr text-dark">
        Update
    </button>
</form>
</br></br>
{% include 'footer.html' %}
{% endblock %}

automobiles/templates/update_vehicle.html
{% extends 'base.html' %}
{% block page_header %}
{% endblock page_header %}
{% block content %}

<br/><h1>Edit Vehicle: {{ vehicle_update }}</h1><br/>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}<br/>
    <button type="submit" class="btn btn-outline-info mb-3 hvr text-dark">Update
    </button>
    <button type="submit" class="btn btn-outline-info mb-3 hvr text-info"
            style="margin-left: 25px;">
        <a href="{% url 'automobiles:home' %}">Home &raquo;&raquo;&raquo;</a>
    </button>
</form>
</br></br>

{% include 'footer.html' %}
{% endblock %}